name: Deploy to Linode
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: unnecessary
        
    - name: Adding Known Hosts
      run: ssh-keyscan -p 2209 -H 23.239.16.189 >> ~/.ssh/known_hosts
    
    - name: Deploy to Linode
      run: |
        ssh -p 2209 www-data@23.239.16.189 << EOF
          cd /var/www/techlifepodcast.com
          git pull
          npm install
          npm run sass-build
          touch tmp/restart.txt
        EOF
