# deploy.yml
name: Deploy to Linode
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PORT: 22
      REMOTE_HOST: www-data@23.239.16.189
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ env.SSH_PORT }} -H ${{ env.REMOTE_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Linode
      run: |
        ssh -p 2209 www-data@23.239.16.189 << EOF
          set -e
          export HOME=/home/www-data
          export NVM_DIR="\$HOME/.nvm"
          [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
          nvm use 16
          cd /var/www/techlifepodcast.com
          git config user.email "deploy@example.com"
          git config user.name "Deploy Bot"
          git fetch origin master
          git reset --hard origin/master
          npm config set cache /var/www/.npm-cache --global
          npm install
          npm run sass-build
          echo "SASS build completed"
          if [ -f public/stylesheets/styles.css ]; then
            echo "CSS file successfully generated"
            ls -l public/stylesheets/styles.css
          else
            echo "Error: CSS file not found at public/stylesheets/styles.css"
            echo "Current directory contents:"
            ls -R
            exit 1
          fi
          mkdir -p /var/www/techlifepodcast.com/tmp
          touch /var/www/techlifepodcast.com/tmp/restart.txt
          echo "Deployment completed successfully"
        EOF
