name: Deploy to Linode
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: unnecessary
        
    - name: Adding Known Hosts
      run: ssh-keyscan -p 2209 -H 23.239.16.189 >> ~/.ssh/known_hosts
    
    - name: Deploy to Linode
      run: |
        ssh -p 2209 www-data@23.239.16.189 << EOF
          cd /var/www/techlifepodcast.com
          git pull || exit 1
          export HOME=/var/www
          npm config set prefix /var/www/.npm-global
          export PATH=/var/www/.npm-global/bin:$PATH
          npm install || exit 1
          npm run sass-build || exit 1
          touch tmp/restart.txt || true
        EOF
