name: Deploy to Server (Simple)

on:
  push:
    branches: [master, deploy-tests]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test SSH Connection
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH connection successful'"

    - name: Deploy to Test Server
      if: github.ref == 'refs/heads/deploy-tests'
      run: |
        echo "Deploying to test server..."
        # Add your test deployment steps here

    - name: Deploy to Production Server
      if: github.ref == 'refs/heads/master'
      run: |
        echo "Deploying to production server..."
        # Add your production deployment steps here