name: Deploy to Server (Simple)

on:
  push:
    branches: [deploy-tests]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/techlifer-linode-github-vasilymac
        chmod 600 ~/.ssh/techlifer-linode-github-vasilymac
        ssh-keygen -y -f ~/.ssh/techlifer-linode-github-vasilymac > ~/.ssh/techlifer-linode-github-vasilymac.pub

    - name: Test SSH connection
      run: ssh -i ~/.ssh/techlifer-linode-github-vasilymac -o StrictHostKeyChecking=no vasily@${{ secrets.HOST }} "echo 'SSH connection successful'"

    - name: Deploy to server
      run: |
        # Add your deployment commands here
        echo "Deployment steps would go here"