name: Deploy to Ubuntu Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug SSH key
      run: |
        if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "SSH_PRIVATE_KEY is set"
          echo "Length of SSH_PRIVATE_KEY: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c) characters"
          echo "First few characters of SSH_PRIVATE_KEY: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | cut -c 1-10)..."
          echo "Does it start with '-----BEGIN'?: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | grep -q '^-----BEGIN' && echo "Yes" || echo "No")"
        else
          echo "SSH_PRIVATE_KEY is not set"
        fi

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/techlifer-linode-github-vasilymac
        chmod 600 ~/.ssh/techlifer-linode-github-vasilymac
        ssh-keygen -y -f ~/.ssh/techlifer-linode-github-vasilymac > ~/.ssh/techlifer-linode-github-vasilymac.pub
        echo "Public key generated from private key:"
        cat ~/.ssh/techlifer-linode-github-vasilymac.pub

    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/techlifer-linode-github-vasilymac -o StrictHostKeyChecking=no -vvv ${{ secrets.USERNAME }}@${{ secrets.HOST }} echo "SSH connection successful"

    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        key_path: ~/.ssh/techlifer-linode-github-vasilymac
        port: 22
        script: |
          echo "Connection successful"
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          
          # Rest of your deployment script...
          cd /var/www/techlifpodcast.com
          git pull origin master
          npm install
          mkdir -p tmp
          touch tmp/restart.txt